[pytest]
addopts = 
    -v
    --alluredir=allure-results
    --strict-markers
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    ui: UI tests
